### ISSUE TITLE
Older images are not cleaned up when building with dev command

### ISSUE THREAD

**Issue by gurgalex** [rovermicrover/siralim-ultimate-dev#1]
I'd like my 10GB of space back please.
![image](https://user-images.githubusercontent.com/28968644/136676996-9679c55b-dead-4325-8b7a-5d5869f1c9e9.png)

**Comment by rovermicrover** [comment]
This just how docker does stuff. It’s up the end user to make decisions about how they want to manager their images. We are already pruning orphaned.
